### PR TITLE
Fix texture cache missing in certain situations after resizing the window

### LINKED ISSUE #977: Toggling fullscreen while the map is open, then closing the map shows black
Another issue caused by invalidated cached textures (due to #923), if you toggle fullscreen while the map is open, then close the map, the gameplay that appears underneath is missing -- it's black instead.

### LINKED ISSUE #988: Regression: Editor tiles stop rendering after resizing window in game options
If you go into the game options in the editor (not just the level options screen, the game options screen that's the same as the one on the title screen), then resize the window or use the 'resize to nearest' graphics option, then exit back to the editor, tiles will stop rendering. If you then either resize the window on this screen, or update the tiles, then they will start rendering again.

`git bisect` has determined that this is a regression from @AllyTally's commit 34cc15505b9f62340c58c10a471136c0a4d94d92, which is from @AllyTally's PR #944.

### PR DESCRIPTION
**Pull request by AllyTally**
## Changes:

This PR fixes an issue where resizing the window can cause textures to not properly recache, rendering invisible.

Fixes #988, fixes #977.

## Legal Stuff:

By submitting this pull request, I confirm that...

- [x] My changes may be used in a future commercial release of VVVVVV
- [x] I will be credited in a `CONTRIBUTORS` file and the "GitHub Friends"
  section of the credits for all of said releases, but will NOT be compensated
  for these changes

### CODE REVIEW

File: desktop_version/src/Screen.cpp [hunk 1]
```diff
@@ -170,9 +170,9 @@ void Screen::ResizeScreen(int x, int y)
     else
     {
         int result = SDL_SetWindowFullscreen(m_window, 0);
-        recacheTextures();
         if (result != 0)
         {
+            recacheTextures();
```
Comment (flibitijibibo) [inline desktop_version/src/Screen.cpp:175]: nit: We could probably remove the `return;` and instead make the `if` just below it an `else if`, so that we effectively move recacheTextures to the bottom and avoid any lurking early return bugs.

**Review by flibitijibibo — APPROVED** [review]
Makes sense to me - even if there are still other places we need to recache this should be okay.
