### PR TITLE
Use variable timestep for `SDL_Delay`

### LINKED ISSUE #1185: Fast-forward does not work in 30-FPS-only mode
The level debugger's fast-forward functionality (accessible by holding down F with the debug menu active) only works in over-30-FPS mode. It does not work if the framerate mode is set to 30 FPS only.

<sub>Thanks to AllyTally for originally reporting this on Discord.</sub>

### PR DESCRIPTION
**Pull request by InfoTeddy**
This fixes a bug where fast-forward wouldn't work in 30-FPS-only mode.

This is because the 30-FPS-only code has a hardcoded check for the number 34, as in 34 milliseconds must pass before the next frame can advance. This is why slowdown still worked, because slowdown means you're waiting longer than 34 ms anyways, but fast-forward tries to wait for only 1 ms, which wouldn't work if the 34 limit was still enforced.

So instead, swap out the 34 with `game.get_timestep()` and this will be fixed.

Fixes #1185.

## Legal Stuff:

By submitting this pull request, I confirm that...

- [x] My changes may be used in a future commercial release of VVVVVV
- [x] I will be credited in a `CONTRIBUTORS` file and the "GitHub Friends"
  section of the credits for all of said releases, but will NOT be compensated
  for these changes unless there is a prior written agreement

### CODE REVIEW

File: desktop_version/src/main.cpp [hunk 1]
```diff
@@ -863,12 +863,14 @@ int main(int argc, char *argv[])
 #else
     while (true)
     {
+        const int timestep = game.get_timestep();
+
         f_time = SDL_GetTicks64();
 
         const Uint64 f_timetaken = f_time - f_timePrev;
```
Comment (Daaaav) [inline desktop_version/src/main.cpp:870]: Nit:
```suggestion
        f_time = SDL_GetTicks64();

        const Uint64 f_timetaken = f_time - f_timePrev;
        const int timestep = game.get_timestep();
```

**Comment by NyakoFox** [comment]
lgtm
