### PR TITLE
Fix entities in the Warp Zone's gray tileset not being gray in the editor

### LINKED ISSUE #372: Enemies, conveyors, and platforms in the Warp Zone gray tileset are not drawn as gray in the editor
They're drawn as gray when in-game, but not in the editor.

### PR DESCRIPTION
**Pull request by AllyTally**
## Changes:

In-level, they were made to be gray in #323. The editor does not reflect this however; they're still shown as
green. For the same reasons in #323, this adds special cases to draw the entities as gray.
Closes #372.
Also, I changed my name in `contributors.txt` to be my username as I didn't feel comfortable with it being my name.

## Legal Stuff:

By submitting this pull request, I confirm that...

- [x] My changes may be used in a future commercial release of VVVVVV (for
  example, a 2.3 update on Steam for Windows/macOS/Linux)
- [x] I will be credited in a `CONTRIBUTORS` file and the "GitHub Friends"
  section of the credits for all of said releases, but will NOT be compensated
  for these changes

### CODE REVIEW

File: desktop_version/src/editor.cpp [hunk 1]
```diff
@@ -2642,6 +2642,12 @@ void editorrender()
 
     int temp2=edentat(ed.tilex+ (ed.levx*40),ed.tiley+ (ed.levy*30));
 
+    // Special case for drawing gray entities
+    int current_room = (ed.levx+(ed.levy*ed.maxwidth));
+    bool custom_gray = ed.level[current_room].tileset == 3 && ed.level[current_room].tilecol == 6;
```
Comment (InfoTeddy) [inline desktop_version/src/editor.cpp:2647]: Should probably bounds-check this index of `ed.level`.
```suggestion
    bool custom_gray = INBOUNDS_ARR(current_room, ed.level)
    && ed.level[current_room].tileset == 3 && ed.level[current_room].tilecol == 6;
```
Same could be said for `graphics.entcolours` below, too, but that code already didn't have a bounds check, so I addressed that in #476.

**Review by InfoTeddy — CHANGES_REQUESTED** [review]
